;; Clean up clutter in the mode line
(diminish 'yas-minor-mode)
(diminish 'company-mode)
(diminish 'whitespace-mode)
(diminish 'flyspell-mode)
(diminish 'smartparens-mode)
(diminish 'prelude-mode)
(diminish 'which-key-mode)
(diminish 'buffer-face-mode)
(diminish 'projectile-mode)
